#!/bin/bash
set -euo pipefail

CLIENT_DIR="${1:?Usage: embed_client.sh <client_dir> <output_header>}"
OUTPUT="${2:?Usage: embed_client.sh <client_dir> <output_header>}"

mkdir -p "$(dirname "$OUTPUT")"

{
    printf "#pragma once\n"
    printf "// Auto-generated by tools/embed_client.sh -- do not edit\n"
    printf "#include <cstddef>\n\n"

    for file in "$CLIENT_DIR"/*; do
        [ -f "$file" ] || continue
        varname=$(basename "$file" | sed 's/[^a-zA-Z0-9]/_/g')

        printf "static constexpr unsigned char %s_data[] = {\n" "$varname"
        # produce hex bytes, 12 per line, with trailing commas
        od -An -tx1 -v < "$file" | tr -d '\r' | awk '
        {
            for (i = 1; i <= NF; i++) {
                buf = buf "0x" $i ", "
                n++
                if (n % 12 == 0) {
                    printf "    %s\n", buf
                    buf = ""
                }
            }
        }
        END {
            if (buf != "") {
                sub(/, $/, "", buf)
                printf "    %s\n", buf
            }
        }'
        printf "};\n"
        printf "static constexpr size_t %s_size = sizeof(%s_data);\n\n" "$varname" "$varname"
    done
} > "$OUTPUT"

echo "Embedded $(find "$CLIENT_DIR" -maxdepth 1 -type f | wc -l) files -> $OUTPUT"
