param(
    [Parameter(Mandatory)][string]$ClientDir,
    [Parameter(Mandatory)][string]$Output
)

$ErrorActionPreference = "Stop"
$outDir = Split-Path $Output -Parent
if ($outDir -and !(Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

$count = 0
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("// Auto-generated by tools/embed_client.ps1 -- do not edit")
[void]$sb.AppendLine("#include <cstddef>")
[void]$sb.AppendLine()

foreach ($file in Get-ChildItem -Path $ClientDir -File) {
    $varname = $file.Name -replace '[^a-zA-Z0-9]', '_'
    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)

    [void]$sb.AppendLine("static constexpr unsigned char ${varname}_data[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 12) {
        $end = [Math]::Min($i + 12, $bytes.Length)
        $hex = ($bytes[$i..($end-1)] | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
        if ($end -lt $bytes.Length) { $hex += "," }
        [void]$sb.AppendLine("    $hex")
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static constexpr size_t ${varname}_size = sizeof(${varname}_data);")
    [void]$sb.AppendLine()
    $count++
}

[System.IO.File]::WriteAllText($Output, $sb.ToString())
Write-Host "Embedded $count files -> $Output"
